### ISSUE TITLE
Does not compile at328p on arduino 1.8.8

### ISSUE THREAD

**Issue by cherkasovn** [NachtRaveVL/PCA9685-Arduino#10]
An example does not compile - Arduino returns the error below:

c:/program files (x86)/arduino/hardware/tools/avr/bin/../lib/gcc/avr/5.4.0/../../../../avr/lib/avr5/crtatmega328p.o:(.init9+0x0): undefined reference to `main'

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino Nano.

**Comment by cherkasovn** [comment]
It was an issue with Arduino itself. A restart of Arduino helped. Weird!

**Comment by NachtRaveVL** [comment]
Weird, indeed! Thanks for at least posting a report, though, just in case others hit the same issue. =)
