### ISSUE TITLE
[Improvement] PIO library support.

### ISSUE THREAD

**Issue by mariusstaicu** [NachtRaveVL/PCA9685-Arduino#14]
I've noticed there are forks of this library available in platformio, however none for esp8266. 
Can you make it available in platformio ? 

https://docs.platformio.org/en/latest/librarymanager/creating.html

Thanks

**Comment by NachtRaveVL** [comment]
I updated the files and it should be compatible with PIO now. I'll be adding it to their registry thingie here in a bit.

**Comment by mariusstaicu** [comment]
Amazing, thank you :+1:
