### ISSUE TITLE
The readRegister operation obscures next write with SoftwareI2C

### ISSUE THREAD

**Issue by svatoun** [NachtRaveVL/PCA9685-Arduino#5]
I am testing PCA9685 library with SoftwareI2C and I've encountered an issue during initializaiton - setPWMFrequency does not work. 
It turned out that at the end of readRegister operation, the I2C does not issue STOP bit; since the next writeRegister issues start bit, the entire transaction (write into the MODE1, which enables setting the prescaler) is rejected and subsequently the prescaler value will be ignored.
The call _i2cWrite->requestFrom() defaults to sending STOP bit after last expected byte from I2C is read.

**Comment by NachtRaveVL** [comment]
Oooooo, good catch!!! I'll be updating this one here in a sec. =)
