### ISSUE TITLE
confirmed for teensy 3.x

### ISSUE THREAD

**Issue by woodygoody** [NachtRaveVL/PCA9685-Arduino#8]
thanks for this great library! it works perfect.

I tested it the other day with an teensy 3.5 with the batching example, only thing i had to change is word to uint16_t in the frontpage as the compiler gave an error which I think had something to do with converting the 32 bit word down to 16 bit.

i checked the output with a logic analyzer, the pulsewidth and phaseshift seem the same compared to a regular arduino.

cheers, niels

**Comment by NachtRaveVL** [comment]
Aww, thanks! =)

I actually changed that to a uint16_t just in the most recent version posted, so closing this. =)
